// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"wechatbot/configs"
	"wechatbot/pkg"
	"wechatbot/third_party"
)

// Injectors from wire.go:

func InitApp(cfg *configs.Config) *pkg.MessagesHandle {
	aiChat := third_party.NewAiChat(cfg)
	messagesHandle := pkg.NewHandle(aiChat, cfg)
	return messagesHandle
}
